services:
  cnergy-backend:
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
        - redis
    networks:
      - cnergy-backend-network

  redis:
    image: redis:6.0.9
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - cnergy-backend-network

  rabbit:
    container_name: cnergy-rabbitmq
    hostname: cnergy-rabbit
    image: heidiks/rabbitmq-delayed-message-exchange:4.0.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - cnergy-backend-network

volumes:
  redis-data:
  rabbitmq-data:

networks:
  cnergy-backend-network:
      driver: bridge
